# Generated by Django 3.2.8 on 2023-05-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='adress',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
