# Generated by Django 3.2.8 on 2023-05-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20230511_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distance',
            field=models.FloatField(default=10000.0),
        ),
        migrations.AddField(
            model_name='order',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_methods',
            field=models.CharField(choices=[('card payment', 'Card Payment'), ('cash payment', 'Cash Payment')], default='cash payment', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
