# Generated by Django 3.2.8 on 2023-05-14 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_lat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_lng',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_lat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_lng',
        ),
    ]
